[package]
org = "ballerina"
name = "http_service_tests"
version = "2.8.3"

[[dependency]]
org = "ballerina"
name = "http_test_common"
repository = "local"
version = "2.8.3"

[[platform.java11.dependency]]
scope = "testOnly"
path = "../../test-utils/build/libs/http-test-utils-2.8.3-SNAPSHOT.jar"
