[package]
org = "ballerina"
name = "http_tests"
version = "2.4.7"

[[platform.java11.dependency]]
scope = "testOnly"
path = "../native/build/libs/http-native-2.4.7.jar"

[[platform.java11.dependency]]
scope = "testOnly"
path = "../test-utils/build/libs/http-test-utils-2.4.7.jar"
